/**
 * @fileoverview gRPC-Web generated client stub for files
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: src/proto/files.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as src_proto_files_pb from '../../src/proto/files_pb';


export class FilesServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorUploadFile = new grpcWeb.MethodDescriptor(
    '/files.FilesService/UploadFile',
    grpcWeb.MethodType.UNARY,
    src_proto_files_pb.FileUpload,
    src_proto_files_pb.FileInfo,
    (request: src_proto_files_pb.FileUpload) => {
      return request.serializeBinary();
    },
    src_proto_files_pb.FileInfo.deserializeBinary
  );

  uploadFile(
    request: src_proto_files_pb.FileUpload,
    metadata: grpcWeb.Metadata | null): Promise<src_proto_files_pb.FileInfo>;

  uploadFile(
    request: src_proto_files_pb.FileUpload,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: src_proto_files_pb.FileInfo) => void): grpcWeb.ClientReadableStream<src_proto_files_pb.FileInfo>;

  uploadFile(
    request: src_proto_files_pb.FileUpload,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: src_proto_files_pb.FileInfo) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/files.FilesService/UploadFile',
        request,
        metadata || {},
        this.methodDescriptorUploadFile,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/files.FilesService/UploadFile',
    request,
    metadata || {},
    this.methodDescriptorUploadFile);
  }

  methodDescriptorGetImage = new grpcWeb.MethodDescriptor(
    '/files.FilesService/GetImage',
    grpcWeb.MethodType.SERVER_STREAMING,
    src_proto_files_pb.FileInfo,
    src_proto_files_pb.ImageFile,
    (request: src_proto_files_pb.FileInfo) => {
      return request.serializeBinary();
    },
    src_proto_files_pb.ImageFile.deserializeBinary
  );

  getImage(
    request: src_proto_files_pb.FileInfo,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<src_proto_files_pb.ImageFile> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/files.FilesService/GetImage',
      request,
      metadata || {},
      this.methodDescriptorGetImage);
  }

}

